ALTER TABLE "Product"
ADD COLUMN "wholesalePrice" DOUBLE PRECISION,
ADD COLUMN "weightGrams" DOUBLE PRECISION,
ADD COLUMN "printHours" DOUBLE PRECISION,
ADD COLUMN "wholesaleEnabled" BOOLEAN NOT NULL DEFAULT false;